// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scheduler.Persistence;

#nullable disable

namespace Scheduler.Persistence.Migrations
{
    [DbContext(typeof(SchedulerDbContext))]
    [Migration("20261005161734_AddAppMeta")]
    partial class AddAppMeta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("Scheduler.Persistence.Entities.AppMetaEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_meta");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.AreaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AreaTypeCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("area_type_code");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("RequiredPerDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("required_per_day");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("AreaTypeCode");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("area");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.AreaTypeEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Code");

                    b.ToTable("area_type");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.BlockedDayEntity", b =>
                {
                    b.Property<string>("StaffId")
                        .HasColumnType("TEXT")
                        .HasColumnName("staff_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.HasKey("StaffId", "Date");

                    b.HasIndex("Date");

                    b.ToTable("blocked_day");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.CalendarDayEntity", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("HolidayName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("holiday_name");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_holiday");

                    b.Property<bool>("IsMakeUpWorkday")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_make_up_workday");

                    b.Property<bool>("IsPublicHoliday")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_public_holiday");

                    b.Property<bool>("Overridden")
                        .HasColumnType("INTEGER")
                        .HasColumnName("overridden");

                    b.HasKey("Date");

                    b.ToTable("calendar_day");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.CarryOverAppliedEntity", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<string>("StaffId")
                        .HasColumnType("TEXT")
                        .HasColumnName("staff_id");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER")
                        .HasColumnName("points");

                    b.HasKey("Year", "Month", "StaffId");

                    b.ToTable("carry_over_applied");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.CarryOverEntity", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<string>("StaffId")
                        .HasColumnType("TEXT")
                        .HasColumnName("staff_id");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER")
                        .HasColumnName("points");

                    b.HasKey("Year", "Month", "StaffId");

                    b.ToTable("carry_over");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.ConstraintDefinitionEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("Metric")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("metric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("ParamCap")
                        .HasColumnType("INTEGER")
                        .HasColumnName("param_cap");

                    b.Property<int?>("ParamDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("param_days");

                    b.Property<string>("ParamDirection")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("param_direction");

                    b.Property<string>("Primitive")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("primitive");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight");

                    b.HasKey("Code");

                    b.ToTable("constraint_definition");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.ConstraintScopeEntryEntity", b =>
                {
                    b.Property<string>("ConstraintCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("constraint_code");

                    b.Property<string>("Dimension")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("dimension");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("ConstraintCode", "Dimension", "Value");

                    b.ToTable("constraint_scope_entry");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.DutyEntity", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<string>("AreaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("area_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("staff_id");

                    b.HasKey("Year", "Month", "AreaId", "Date");

                    b.HasIndex("Date");

                    b.HasIndex("StaffId");

                    b.ToTable("duty");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.EligibilityEntity", b =>
                {
                    b.Property<string>("RankCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("rank_code");

                    b.Property<string>("AreaTypeCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("area_type_code");

                    b.Property<bool>("Eligible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eligible");

                    b.HasKey("RankCode", "AreaTypeCode");

                    b.ToTable("eligibility");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.FairnessPointTableEntity", b =>
                {
                    b.Property<string>("PointType")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("point_type");

                    b.Property<string>("Today")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("today");

                    b.Property<string>("Tomorrow")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("tomorrow");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER")
                        .HasColumnName("points");

                    b.HasKey("PointType", "Today", "Tomorrow");

                    b.ToTable("fairness_point_table");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.MonthlyOverrideEntity", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<string>("RankCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("rank_code");

                    b.Property<int>("QuotaCap")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quota_cap");

                    b.HasKey("Year", "Month", "RankCode");

                    b.ToTable("monthly_override");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.PointRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("QuotaHoliday")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quota_holiday");

                    b.Property<int>("QuotaWeekday")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quota_weekday");

                    b.Property<int>("SaturdayBonusPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("saturday_bonus_points");

                    b.Property<int>("SaturdayBonusWindowDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("saturday_bonus_window_days");

                    b.HasKey("Id");

                    b.ToTable("point_rule");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.RankEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PointType")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("point_type");

                    b.Property<int?>("QuotaCap")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quota_cap");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Code");

                    b.HasIndex("GroupCode");

                    b.ToTable("rank");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.RankGroupEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Code");

                    b.ToTable("rank_group");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.ScheduleEntity", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<string>("PublishedAt")
                        .HasMaxLength(28)
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at");

                    b.Property<int>("PublishedRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("published_revision");

                    b.Property<int>("PublishedVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("published_version");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Year", "Month");

                    b.ToTable("schedule");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.SolverJobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<double?>("ElapsedSec")
                        .HasColumnType("REAL")
                        .HasColumnName("elapsed_sec");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<string>("FinishedAt")
                        .HasMaxLength(28)
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<int?>("HardConstraintCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hard_constraint_count");

                    b.Property<double?>("LastBestBound")
                        .HasColumnType("REAL")
                        .HasColumnName("last_best_bound");

                    b.Property<double?>("LastBestObjective")
                        .HasColumnType("REAL")
                        .HasColumnName("last_best_objective");

                    b.Property<int?>("LastSolutionCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_solution_count");

                    b.Property<int?>("LastVariantIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_variant_index");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<int?>("ScaleAreas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scale_areas");

                    b.Property<int?>("ScaleDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scale_days");

                    b.Property<int?>("ScaleStaff")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scale_staff");

                    b.Property<int?>("ScaleVariables")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scale_variables");

                    b.Property<int?>("SoftConstraintCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("soft_constraint_count");

                    b.Property<string>("StartedAt")
                        .HasMaxLength(28)
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("TimeLimitSecPerVariant")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_limit_sec_per_variant");

                    b.Property<int>("VariantCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("variant_count");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("solver_job");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.SolverJobWarningEntity", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<int>("Seq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seq");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.HasKey("JobId", "Seq");

                    b.ToTable("solver_job_warning");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.StaffEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_no");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RankCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rank_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNo")
                        .IsUnique();

                    b.ToTable("staff");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.VariantDutyEntity", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<string>("VariantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("variant_id");

                    b.Property<string>("AreaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("area_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("staff_id");

                    b.HasKey("JobId", "VariantId", "AreaId", "Date");

                    b.ToTable("variant_duty");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.VariantEntity", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("HardViolationCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hard_violation_count");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<double>("MetricAreaConsistency")
                        .HasColumnType("REAL")
                        .HasColumnName("metric_area_consistency");

                    b.Property<double?>("MetricFairnessPoint")
                        .HasColumnType("REAL")
                        .HasColumnName("metric_fairness_point");

                    b.Property<double>("MetricQuotaFairness")
                        .HasColumnType("REAL")
                        .HasColumnName("metric_quota_fairness");

                    b.Property<double>("MetricRankPreference")
                        .HasColumnType("REAL")
                        .HasColumnName("metric_rank_preference");

                    b.Property<int>("MetricVacancies")
                        .HasColumnType("INTEGER")
                        .HasColumnName("metric_vacancies");

                    b.Property<double>("SoftScore")
                        .HasColumnType("REAL")
                        .HasColumnName("soft_score");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("JobId", "Id");

                    b.ToTable("variant");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.VariantWeightEntity", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<string>("VariantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("variant_id");

                    b.Property<string>("ConstraintCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("constraint_code");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL")
                        .HasColumnName("multiplier");

                    b.HasKey("JobId", "VariantId", "ConstraintCode");

                    b.ToTable("variant_weight");
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.AreaEntity", b =>
                {
                    b.HasOne("Scheduler.Persistence.Entities.AreaTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("AreaTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.CarryOverAppliedEntity", b =>
                {
                    b.HasOne("Scheduler.Persistence.Entities.ScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("Year", "Month")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.CarryOverEntity", b =>
                {
                    b.HasOne("Scheduler.Persistence.Entities.ScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("Year", "Month")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.ConstraintScopeEntryEntity", b =>
                {
                    b.HasOne("Scheduler.Persistence.Entities.ConstraintDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("ConstraintCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.DutyEntity", b =>
                {
                    b.HasOne("Scheduler.Persistence.Entities.ScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("Year", "Month")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.RankEntity", b =>
                {
                    b.HasOne("Scheduler.Persistence.Entities.RankGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.SolverJobWarningEntity", b =>
                {
                    b.HasOne("Scheduler.Persistence.Entities.SolverJobEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.VariantDutyEntity", b =>
                {
                    b.HasOne("Scheduler.Persistence.Entities.VariantEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId", "VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.VariantEntity", b =>
                {
                    b.HasOne("Scheduler.Persistence.Entities.SolverJobEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scheduler.Persistence.Entities.VariantWeightEntity", b =>
                {
                    b.HasOne("Scheduler.Persistence.Entities.VariantEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId", "VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
